package g2

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"strings"

	aquaregistry "github.com/aquaproj/aqua/v2/pkg/config/registry"
	aquag2 "github.com/aquaproj/aqua/v2/pkg/g2"
	"go.yaml.in/yaml/v3"
)

// RenamePackage puts the package's definition under the name its repository has now, in a
// pull request into the branch holding it.
//
// The branch doesn't move, which is what naming it after an id is for: a rename used to
// carry the whole branch over, and everything that had written the old name down was left
// pointing at nothing. What has to change is the definition, because the definition is the
// only thing that says which package the branch holds -- one still naming the old package
// would be found under a name nobody uses, and a run asking for the new name would find no
// branch and make a second one.
//
// The old name becomes an alias, which is how a configuration still asking for it resolves.
//
// It returns the definition as the pull request writes it, and nil when there was nothing to
// do: a definition that already names the new package is what a second run of the same
// rename sees.
func (c *Client) RenamePackage(ctx context.Context, logger *slog.Logger, from, to string) (*aquag2.Config, error) {
	branch, ok := c.Branch(from)
	if !ok {
		return nil, fmt.Errorf("%w: %s", errNoBranchToRename, from)
	}
	head, _ := c.HeadBranch(from)
	parent, err := c.BranchSHA(ctx, branch)
	if err != nil {
		return nil, err
	}
	if parent == "" {
		return nil, fmt.Errorf("%w: %s", errNoBranchToRename, from)
	}

	cfg, err := c.ConfigOnRef(ctx, branch)
	if err != nil {
		return nil, err
	}
	if cfg == nil {
		return nil, fmt.Errorf("%w: %s", errNoConfigToRename, from)
	}
	if cfg.Name == to {
		return nil, nil //nolint:nilnil // nothing to do, which is not a definition
	}
	content, err := renamedConfig(cfg, from, to)
	if err != nil {
		return nil, err
	}

	title := fmt.Sprintf("fix(%s): rename the package to %s", from, to)
	if err := c.Commit(ctx, head, parent, title, []*File{{
		Path:    ConfigFileName,
		Content: content,
	}}); err != nil {
		return nil, fmt.Errorf("commit the renamed definition: %w", err)
	}
	pr, err := c.CreatePullRequestFrom(ctx, logger, head, branch, title, renameBody(from, to))
	if err != nil {
		return nil, fmt.Errorf("open the pull request that renames the package: %w", err)
	}
	logger.Info("opened the pull request that renames the package",
		"from", from, "to", to, "number", pr.GetNumber())
	return cfg, nil
}

// renameBody says what the pull request does and what waits on it.
func renameBody(from, to string) string {
	return fmt.Sprintf(`Generated by ar2.

%s answers to %s now. The definition on this branch is what says which package the branch
holds, so it is what the rename changes; the branch itself is named after the package's id
and doesn't move.

The old name is kept as an alias, which is how a configuration still asking for %s resolves.

Until this merges, the registry still holds the package under %s: a run asking for the new
name finds no branch for it.
`, from, to, from, from)
}

// renamedConfig is the definition under the new name.
//
// The old name becomes an alias, kept alongside the ones it already had rather than
// replacing them: a package renamed twice has to answer to both of its old names, and a
// definition recording only the last one would leave the older pointing at a name
// nothing holds any more.
func renamedConfig(cfg *aquag2.Config, from, to string) (string, error) {
	if cfg == nil {
		return "", fmt.Errorf("%w: %s", errNoConfigToRename, from)
	}
	owner, name, err := splitRepo(to)
	if err != nil {
		return "", err
	}
	cfg.RepoOwner, cfg.RepoName = owner, name
	if cfg.Name != "" {
		cfg.Name = to
	}
	if !hasAlias(cfg, from) {
		cfg.Aliases = append(cfg.Aliases, &aquaregistry.Alias{Name: from})
	}
	b, err := yaml.Marshal(cfg)
	if err != nil {
		return "", fmt.Errorf("marshal the definition of the renamed package: %w", err)
	}
	return string(b), nil
}

// splitRepo reads the owner and the repository out of a package name.
//
// A package name is usually the repository it comes from, and sometimes a command inside
// one: kubernetes/kubernetes/kubectl is the kubectl of kubernetes/kubernetes. The first
// two parts are the repository either way.
func splitRepo(pkgName string) (string, string, error) {
	parts := strings.SplitN(pkgName, "/", 3) //nolint:mnd
	if len(parts) < 2 || parts[0] == "" || parts[1] == "" {
		return "", "", fmt.Errorf("%w: %s", errNotARepoName, pkgName)
	}
	return parts[0], parts[1], nil
}

// hasAlias reports whether the definition already names it.
func hasAlias(cfg *aquag2.Config, name string) bool {
	for _, alias := range cfg.Aliases {
		if alias != nil && alias.Name == name {
			return true
		}
	}
	return false
}

// ErrNoBranchToRename says the rename failed because the registry doesn't hold the
// package.
//
// Which is not a failure of the rename so much as a rename with nothing to do: what the
// caller has to move is the package's place in its own records, and the registry only ever
// sees the new name.
func ErrNoBranchToRename(err error) bool {
	return errors.Is(err, errNoBranchToRename)
}

var (
	// errNoBranchToRename is what a rename of a package the registry doesn't hold gets.
	// There is nothing to carry over, and generating it under the new name is what the
	// ordinary run does.
	errNoBranchToRename = errors.New("the package has no branch to rename")
	// errNoConfigToRename is what a branch with no definition gets. Its versions were
	// never generated, so the new name has nothing to inherit either.
	errNoConfigToRename = errors.New("the package's branch has no definition")
	// errNotARepoName says a package name doesn't name a repository, which is what the
	// renamed definition has to record.
	errNotARepoName = errors.New("the package name doesn't name a repository")
)
